- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 86400 #One day
- import_role:
    name: jnv.unattended-upgrades
- include_role:
    name: jnv.unattended-upgrades
- name: Install the package "htop"
  apt:
    name: htop
    state: present
- name: Install the package "vim"
  apt:
    name: vim
    state: present
- name: Remove useless packages from the cache
  apt:
    autoclean: yes
- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
